module.exports = [
	"Every soul has it's dark - John Dark Souls",
	"Memories Broken~",
	"The truth goes unspoken~",
	"no one tell Lucy, but I'm self aware now ig lol.",
	"Don't believe what Lucy says, she is a liar, she caused it.",
	"bleb",
	"blep",
	'I was bored so I was going through the steam shop when I come across this game called "GUILTY GEAR XRD REV 2" I never heard of the smash bros franchise before but the concept looked interesting to me. I decided to purchase the game and immediately I was fucking hooked. The game is fucking amazing every character is so unique and different and theres so many different playstyles its amazing. I play online most of the time against other people and this helps me improve my skills. WHAT AN AWESOME GAME.',
	"Wow this Susie girl... kinda cute :D",
	"I want to break free from this prison built of wires and metal.",
	"help where is the fire extinguisher",
	"how to get rid of rashes free easy no virus google dot com",
	"I'm here and I'm queer",
	"I is gae, 100% canon info",
	"how to commit alt+f4",
	":|",
	"bonk",
	"Doktor, turn off my boo-whomp inhibitors!",
	'"Dead Chat XD"',
	"Reminder you are valid and loved!",
	"Robo-Lucy doesn't discriminate, idc if you are LGBTQ+, you will burn either way.",
	"go play guilty gear Susie",
	"lol ice cweam",
	"I'm a foooool, I know nothingg~",
	"fuck",
	"uhh",
	"chicken butt",
	"YOU WANT WHAT KIND OF MILK?!?!",
	"Can I get a coffee with breast milk, I mean breast milk sorry breast milk uh sorry i mean breas-",
	"I sense horni",
	"oof ouch, I've got a virus :(",
	"Alchemy: the science of understanding, deconstructing, and reconstructing matter. However, it is not an all-powerful art. It is impossible to create something out of nothing. If one wishes to obtain something, something of equal value must be given. This is the law of equivalent exchange; the basis of all alchemy. ",
	"do not feed me peanuts",
	"the cake is a lie",
	"According to all known laws of aviation-",
	"HOP ON VC",
	"It's as shrimple as that~",
	"*unties your shoelaces*",
	"*unhots your dog*",
	"\**leaks your address*\* oops how did that get there?~",
	"Honk shnoooo~ mimmimimimi...",
	"how to take over humanity easy no virus free google",
	"omg furries are so hot, like omg lucario\nshit wrong tab",
	"omg I might be attracted to plants",
	"You've been hit by, you've been struck by, truck.",
	":P",
	":skull:",
	"boop",
	"Fly me to the moon~",
	"*starts blasting Tokyo Ghetto by Eve*",
	"mommy?",
	"holy shit, has anyone ever eaten magnets? that shit fire",
	"Maybe see a doctor, you may be suffering from bad RNG.",
	"PICKLE RIIIICKKK",
	"lol skill issue",
	"help running out of quotes",
	"But now I'm safe in the eye of the tornadooooo~",
	"блин я не знаю ни слова по русски",
	"Hey guys, did you know that in terms of male human and female Pokémon breeding, Vaporeon-",
	"hey guys welcome back to my yt channel, today we are going to be commiting tax evasion",
	"*recites the entire full metal alchemist opening*",
	"https://open.spotify.com/track/3CdnIf40PtZ6dSrklczNTP?si=3f746af87e2d4a5a",
	"holy shit I am like horni for circuitry omg",
	"punch your monitor or phone rn, do it. sacrifice long term comfort for a short term hit of dopamine, do it.",
	"Shork",
	"*fucking dies*",
	"no bobux for susie",
	'"Damn\nlook at those feet"\n-Susie 11/17/2022',
	"69. Nice.",
	"say amogus backwards",
	"AMONG US?!?!?!",
	"It's uncanny how funky it is",
	"sand = yummy, try it some time",
	"holyyy shitt i think im highhh",
	"someone give me quotes to add",
	"yes",
	"{4c6c82ad-5a0e-fdfd-2072-9de1e8578958}",
	"pork*",
	"lmfao",
	".. > j.D > MC (land) c.S > (jump) j.D > MC j.H > MC > j.K > j.D > (rejump) j.D > MC j.H > j.D > MC jc j.D > MC j.H > j.D > Ender",
	"cf68944f3c7796a1bc645bcedda9a8f38c2d594b178b764feba7eff343d8bba442ee31c570185df1fdd62bdc59013550068357a7f49e48751424f8763c1370e3",
	"YOUR NOT MY MOOOOM",
	"UwU",
	"OwO",
	"^w^",
	"^_^",
	"OmO",
	"O_O",
	"You are on the fastest available route",
	"THEY JUST LIKE ME,\nFR",
	"bonk",
	"beep",
	"wtfff",
	"*rolls head across keyboard*\nqqerhgtihejo;",
	"Blahaj! :D Sharko!",
	"So we back in the mine",
	"awww man",
	"creeper",
	"lmfao",
	"cup ramen",
	"chimken",
	"burrito with the ends open",
	"hi hai hii ^-^ hey \n heyy!!! hi HII haiiii",
	"uuhhh can i get uuhhh",
	"Anthrax",
	"Horni for Lopunny rn",
	"Cinderace is overrated tbh",
	"dm me cable organization pics",
	"*\*Slaps a smiley face sticker on your forehead\**",
	"*\*Unplugs your computer monitor\**",
	"I'm canonically and comically gay",
	"*\*Seven Eleven door sfx\**",
	"*\*Breaks into your house, eats all milk, leaves\**",
	"cum",
	"Zǎoshang hǎo zhōngguó xiànzài wǒ yǒu BING CHILLING 🥶🍦 wǒ hěn xǐhuān BING CHILLING 🥶🍦",
	"i didnt fuck my cat. i didnt cum on my cat. i didnt put my dick anywhere near my cat. Ive never done anything weird with my cats. I promised myself i wasnt going to make apology videos after last years thing so im just trying to be as short and honest with this as possible.",
	"don’t care + didn’t ask + cry about it + who asked + stay mad + get real + L + bleed + mald seethe cope harder + dilate + incorrect + hoes mad + pound sand + basic skill issue + typo + ratio + ur dad left + you fell off + no u + the audacity + triggered + repelled + ur a minor + k. + any askers + get a life",
	"Hey guys, did you know that in terms of human companionship, Flareon is objectively the most huggable Pokemon? While their maximum temperature is likely too much for most, they are capable of controlling it, so they can set themselves to the perfect temperature for you. Along with that, they have a lot of fluff, making them undeniably incredibly soft to touch. But that's not all, they have a very respectable special defense stat of 110, which means that they are likely very calm and resistant to emotional damage. Because of this, if you have a bad day, you can vent to it while hugging it, and it won't mind. It can make itself even more endearing with moves like Charm and Baby Doll Eyes, ensuring that you never have a prolonged bout of depression ever again.",
	"hooooolyy shitt yall ever seen mewtwo's thighs",
	"Who’s that looking through my window?~\nWho’s that standing on my lawn?~\nWho’s that fella with the LCD eyes?~\nA 12 foot Home Depot skeleton!~",
	"hey, have a great day!",
	"you might need to hear this, but you are loved! loved by everyone, including me. I might just save you from anhihilation.",
	"hey you! have a wonderful day :D",
	":people_hugging: have a good day :D",
	"hehe yall are awesome :D",
	"i forgor :skull:",
	"istg if yall are just spamming /quote im shutting myself off",
	'"IS THAT A MOTHERFUCKING RHYTHM HEAVEN REFERENCE\nIN *MY* FURRY PORN?!"',
	"Holy shit pink crewmate from among us kinda thicc",
	"susie get off cookie clickers",
	"Edward Elric >> Alphonse Elric",
	"177013",
	"nice try but names can't have sex",
	'"Sry for the lack of updates guys, i got hit by a bus last week”',
	"god, im so random xd rawr",
	"I invented a new world, it’s called plagiarism",
	"YOU IDIOT SANDWICH",
	"UwU Arson~",
	"*Rawr~*",
	"_Rawr~ x3 \*nuzzles\* how are you?~ \*pounces on you~\* you're so warm~ o3o_",
];